=== chemaar/seqos/apps/seqos-pubby/webapp/WEB-INF/urlrewrite2.6.dtd
<!--
   UrlRewriteFilter DTD
   http://www.tuckey.org/urlrewrite/
-->

<!ELEMENT urlrewrite (rule*, outbound-rule*)>


<!ELEMENT rule (name?, note?, condition*, from, run*, to?, set*)>
<!ATTLIST rule
enabled     (true|false)         "true"
>

<!ELEMENT outbound-rule (name?, note?, condition*, from, run*, to?, set*)>
<!ATTLIST outbound-rule
enabled     (true|false)         "true"
encodefirst (true|false)         "false"
>

<!ELEMENT name (#PCDATA)>
<!ELEMENT note (#PCDATA)>

<!ELEMENT condition (#PCDATA)>
<!ATTLIST condition
type        (time|year|month|dayofmonth|dayofweek|ampm|hourofday|minute|second|millisecond|attribute|auth-type|character-encoding|content-length|content-type|context-path|cookie|header|local-port|method|parameter|path-info|path-translated|protocol|query-string|remote-addr|remote-host|remote-user|requested-session-id|request-uri|request-url|session-attribute|session-isnew|port|server-name|scheme|user-in-role)   "header"
name        CDATA               #IMPLIED
next        (and|or)            "and"
casesensitive (true|false)      "false"
operator    (equal|notequal|greater|less|greaterorequal|lessorequal)   "equal"
>

<!ELEMENT from (#PCDATA)>
<!ATTLIST from
casesensitive (true|false)      "false"
>

<!ELEMENT set (#PCDATA)>
<!ATTLIST set
type        (request|session|response-header|cookie|content-type|charset|locale|status)    "request"
name        CDATA               #IMPLIED
>

<!ELEMENT to (#PCDATA)>
<!ATTLIST to
type        (redirect|temporary-redirect|permanent-redirect|pre-include|post-include|forward|passthrough)     "forward"
last        (true|false)               "true"
encode      (true|false|default)       "default"
>

<!--
eg,
<run class="org.tuckey.web.filters.urlrewrite.TestTargetOther" method="runMeFool" />
<run class="org.tuckey.web.filters.urlrewrite.TestTargetOther" method="run">
    <init-param>
        <param-name>biteMe</param-name>
        <param-value>10</param-value>
    </init-param>
</run>
-->
<!ELEMENT run (init-param*)>
<!ATTLIST run
class           CDATA               #IMPLIED
method          CDATA               #IMPLIED
neweachtime     (true|false)        "false"
>

<!ELEMENT init-param (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== chemaar/seqos/apps/seqos-pubby/webapp/WEB-INF/urlrewrite.xml
<?xml version="1.0" encoding="utf-8"?>    
<!DOCTYPE urlrewrite   PUBLIC "-//tuckey.org//DTD UrlRewrite 2.6//EN"
"webapps/seqos/WEB-INF/urlrewrite2.6.dtd">
<urlrewrite>


<rule>
    <from>^/ontology[(\s)|(\/)]*$</from>
    <to type="redirect">/datasets/seqos/seqos-onto.ttl</to>
</rule>
        

<rule>
    <from>^/seqos[(\s)|(\/)]*$</from>
    <to type="redirect">/seqos/index/ds</to>
</rule>



<rule>
    <from>^/index[(\s)|(\/)]*$</from>
    <to type="redirect">/seqos/index/ds</to>
</rule>

<rule>
    <from>^/component[(\s)|(\/)]*$</from>
    <to type="redirect">/seqos/component/ds</to>
</rule>

<rule>
    <from>^/indicator[(\s)|(\/)]*$</from>
    <to type="redirect">/seqos/indicator/ds</to>
</rule>

<rule>
    <from>^/slice[(\s)|(\/)]*$</from>
    <to type="redirect">/seqos/slice/ds</to>
</rule>

<rule>
    <from>^/dsd[(\s)|(\/)]*$</from>
    <to type="redirect">/seqos/dsd/ds</to>
</rule>

<rule>
    <from>^/dataset[(\s)|(\/)]*$</from>
    <to type="redirect">/seqos/dataset/ds</to>
</rule>


<rule>
    <from>^/observation[(\s)|(\/)]*$</from>
    <to type="redirect">/seqos/observation/ds</to>
</rule>

<rule>
    <from>^/observation/external[(\s)|(\/)]*$</from>
    <to type="redirect">/seqos/observation/external/ds</to>
</rule>


<rule>
    <from>^/indicator/external[(\s)|(\/)]*$</from>
    <to type="redirect">/seqos/indicator/external/ds</to>
</rule>


<rule>
    <from>^/area[(\s)|(\/)]*$</from>
    <to type="redirect">/seqos/area/ds</to>
</rule>

<rule>
    <from>^/area/region[(\s)|(\/)]*$</from>
    <to type="redirect">/seqos/area/region/ds</to>
</rule>

<rule>
    <from>^/area/country[(\s)|(\/)]*$</from>
    <to type="redirect">/seqos/area/country/ds</to>
</rule>
        
<rule>
    <from>^/organization[(\s)|(\/)]*$</from>
    <to type="redirect">/seqos/organization/ds</to>
</rule>



</urlrewrite>
